#!/usr/bin/env python

import wx
import jmage.ui

class HeadRowClass(jmage.ui.Grid.RowPanel):
    def PopulateRow(self, row, data_row):
      button = wx.Button(row, -1, "-")
      row.Add(button)
      self.Bind(wx.EVT_BUTTON, self.OnRemove, button)
      for el in data_row[:2]:
        tc = wx.TextCtrl(row)
        tc.SetValue(el)
        row.Add(tc)

    def UpdateRow(self, row, data_row):
      windows = row.GetWindows()
      for i in range(1,len(windows)):
        windows[i].SetValue(data_row[i])

    def OnRemove(self, e):
      i = self.Index(e.GetEventObject().GetParent())
      data.pop(i)
      self.GetParent().Remove(i)

class MainRowClass(jmage.ui.Grid.RowPanel):
    def PopulateRow(self, row, data_row):
      for el in data_row[2:]:
        tc = wx.TextCtrl(row)
        tc.SetValue(el)
        row.Add(tc)

    def UpdateRow(self, row, data_row):
      windows = row.GetWindows()
      for i in range(len(windows)):
        windows[i].SetValue(data_row[i + 2])

data = []
for i in range(8):
  row = []
  for j in range(8):
    row.append("%i,%i" % (i,j))
  data.append(row)

class MyFrame(wx.Frame):
  def __init__(self, *args, **kwargs):
    super(MyFrame, self).__init__(*args, **kwargs)

    self.grid = jmage.ui.Grid(HeadRowClass, MainRowClass, self)

    col_head1 = self.grid.GetColHead1()
    for i in range(3): 
      tc = wx.TextCtrl(col_head1)      
      tc.SetValue("head %i" % i)
      col_head1.Add(tc)

    col_head2 = self.grid.GetColHead2()
    for i in range(2,8): 
      tc = wx.TextCtrl(col_head2)      
      tc.SetValue("head %i" % i)
      col_head2.Add(tc)

    self.grid.RegisterData(data)

    self.Show()

if __name__ == '__main__':
  app = wx.App()
  frame = MyFrame(None, size=(300,200))
  app.MainLoop()
