#!/usr/bin/env python

import wx
import jmage.ui

class LPanel(jmage.ui.GridPanel):
  def CreateHeader(self, item):
    header = self.NewHeader()
    for i in range(3): 
      tc = wx.TextCtrl(header)
      tc.SetValue(item[i])
      header.Add(tc)

    return header

  def CreateRow(self, item):
    row = self.NewRow()
    button = wx.Button(row, -1, "-")
    row.Add(button)
    self.Bind(wx.EVT_BUTTON, self.OnRemove, button)
    for el in item[:2]:
      tc = wx.TextCtrl(row)
      tc.SetValue(el)
      row.Add(tc)

    return row

  def UpdateRow(self, i, item):
    windows = self.windows[i].GetWindows()
    for j in range(1, len(windows)):
      windows[j].SetValue(item[j - 1])

  def OnRemove(self, e):
    i = self.Index(e.GetEventObject().GetParent())
    self.GetParent().Remove(i)

class RPanel(jmage.ui.GridPanel):
  def CreateHeader(self, item):
    header = self.NewHeader()
    for i in range(2, 8): 
      tc = wx.TextCtrl(header)
      tc.SetValue(item[i])
      header.Add(tc)

    return header

  def CreateRow(self, item):
    row = self.NewRow()
    for el in item[2:]:
      tc = wx.TextCtrl(row)
      tc.SetValue(el)
      row.Add(tc)

    return row

  def UpdateRow(self, i, item):
    windows = self.windows[i].GetWindows()
    for j in range(len(windows)):
      windows[j].SetValue(item[j + 2])

data = []
head = []
for i in range(8):
  head.append("head %i" % i)
data.append(head)

for i in range(1,8):
#for i in range(100):
  row = []
  for j in range(8):
    row.append("%i,%i" % (i,j))
  data.append(row)

class MyFrame(wx.Frame):
  def __init__(self, *args, **kwargs):
    super(MyFrame, self).__init__(*args, **kwargs)

    self.grid = jmage.ui.Grid(self)

    grid_pane = LPanel(self.grid)
    self.grid.Add(grid_pane)
    grid_pane = RPanel(self.grid)
    self.grid.Add(grid_pane)
    self.grid.RegisterData(data)

    self.Show()

if __name__ == '__main__':
  app = wx.App()
  frame = MyFrame(None, size=(300,200))
  #frame = MyFrame(None, size=(300,220))
  app.MainLoop()
