set(LIBSNDFILE_DEFINITIONS "")

find_path(LIBSNDFILE_INCLUDE_DIR sndfile.h)

find_library(LIBSNDFILE_LIBRARY sndfile)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LibSndFile DEFAULT_MSG
  LIBSNDFILE_INCLUDE_DIR LIBSNDFILE_LIBRARY)

mark_as_advanced(LIBSNDFILE_INCLUDE_DIR LIBSNDFILE_LIBRARY)

set(LIBSNDFILE_LIBRARIES ${LIBSNDFILE_LIBRARY})
set(LIBSNDFILE_INCLUDE_DIRS ${LIBSNDFILE_INCLUDE_DIR})
