set(LIBSAMPLERATE_DEFINITIONS "")

find_path(LIBSAMPLERATE_INCLUDE_DIR samplerate.h)

find_library(LIBSAMPLERATE_LIBRARY samplerate)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(LIBSAMPLERATE DEFAULT_MSG
  LIBSAMPLERATE_INCLUDE_DIR LIBSAMPLERATE_LIBRARY)

mark_as_advanced(LIBSAMPLERATE_INCLUDE_DIR LIBSAMPLERATE_LIBRARY)

set(LIBSAMPLERATE_LIBRARIES ${LIBSAMPLERATE_LIBRARY})
set(LIBSAMPLERATE_INCLUDE_DIRS ${LIBSAMPLERATE_INCLUDE_DIR})
